- arguments: ["-XOverloadedStrings"]
- ignore:
    name: Use camelCase
- ignore:
    name: Redundant do
- ignore:
    name: Reduce duplication
- ignore:
    name: Redundant bracket
- ignore:
    name: Unused LANGUAGE pragma
- ignore:
    name: Redundant variable capture
- ignore:
    name: Use isAsciiUpper