name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.6.5", "9.6.7"]
        cabal: ["3.10.3.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cabal update
        run: cabal update

      - name: Install tools (fourmolu, hlint)
        run: |
          cabal install fourmolu hlint --overwrite-policy=always
          echo "$HOME/.cabal/bin" >> "$GITHUB_PATH"

      - name: Format check
        run: fourmolu -m check app src test

      - name: Lint
        run: hlint app src test

      - name: Build (-f -icu)
        run: cabal build -f -icu all -j

      - name: Test (-f -icu)
        run: cabal test -f -icu all -j
