name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.6.5", "9.6.7", "9.8.2", "9.10.1", "9.12.2"]
        cabal: ["3.12.1.0"]
        os: [ubuntu-latest]
        include:
          # Test latest GHC on multiple platforms
          - ghc: "9.12.2"
            cabal: "3.12.1.0"
            os: macos-latest
          - ghc: "9.12.2"
            cabal: "3.12.1.0"
            os: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure Cabal
        run: |
          cabal configure --enable-tests --enable-benchmarks
          cabal update

      - name: Cache Cabal Store
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.os == 'Windows' && '~\\AppData\\Roaming\\cabal' || '~/.cabal' }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-${{ hashFiles('**/*.cabal', 'cabal.project*') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Install dependencies
        run: cabal build --dependencies-only all

      - name: Install tools (fourmolu, hlint)
        run: |
          cabal install fourmolu hlint --overwrite-policy=always
        shell: bash

      - name: Add cabal bin to PATH (Unix)
        if: runner.os != 'Windows'
        run: echo "$HOME/.cabal/bin" >> "$GITHUB_PATH"

      - name: Add cabal bin to PATH (Windows)
        if: runner.os == 'Windows'
        run: echo "$env:APPDATA\cabal\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Format check
        run: |
          if command -v fourmolu >/dev/null 2>&1; then
            fourmolu -m check app src test
          else
            echo "Warning: fourmolu not found, skipping format check"
          fi
        shell: bash
        continue-on-error: true

      - name: Lint
        run: |
          if command -v hlint >/dev/null 2>&1; then
            hlint app src test
          else
            echo "Warning: hlint not found, skipping lint check"
          fi
        shell: bash
        continue-on-error: true

      - name: Build with strict warnings (-Wall -Werror, -f -icu)
        run: cabal build -f -icu all -j --ghc-options="-Wall -Werror"

      - name: Test (-f -icu)
        run: cabal test -f -icu all -j --test-show-details=streaming

      - name: Install ICU (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu-dev

      - name: Install ICU (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install icu4c
          if [ -d "/opt/homebrew/opt/icu4c" ]; then
            echo "PKG_CONFIG_PATH=/opt/homebrew/opt/icu4c/lib/pkgconfig" >> $GITHUB_ENV
          else
            echo "PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig" >> $GITHUB_ENV
          fi

      - name: Build with ICU
        if: runner.os != 'Windows'
        run: |
          cabal build -f +icu all -j || echo "ICU build failed, continuing..."
          cabal test -f +icu all -j --test-show-details=streaming || echo "ICU tests failed, continuing..."
        continue-on-error: true
